version: '2.4'

services:
  users:
    volumes:
      - "./src/Sannel.House.Users/app_config:/app/app_config"
      - "./src/Sannel.House.Users/app_data:/app/app_data"
    networks:
      housenet:
        ipv4_address: "10.10.200.3"

networks:
  housenet:
    ipam:
      config:
        - subnet: 10.10.200.0/24
          gateway: 10.10.200.1

