version: '2.4'

services:
  users:
    image: ${DOCKER_REGISTRY}sannelhouseusers:1.0.0-${SANNEL_ARCH}
    build:
      context: .
      dockerfile: src/Sannel.House.Users/Dockerfile
    environment:
      - ASPNETCORE_URLS=https://+:443
    labels:
      org.shabadu.hostname: "users.house.dev.local"
      org.shabadu.cert: "src/Sannel.House.Users/app_config/house.dev.local.cer"