version: '3.6'

services:
  users:
    image: ${DOCKER_REGISTRY}sannelhouseusers:build-${SANNEL_VERSION}-${SANNEL_ARCH}
    build:
      context: .
      dockerfile: src/Sannel.House.Users/Dockerfile
      args:
        USER: "${USER}"