version: '3.6'

services:
  users:
    image: sannel/house/users:dev
    build:
      context: .
      dockerfile: src/Sannel.House.Users/Dockerfile
    ports:
      - "8443:8443"
      - "8080:8080"
