---
Db:
  Provider: sqlite
  ConnectionString: Data Source=app_data/data.db
  SeedDb: true
  DbSeed:
    Scopes:
    - Name: openid
      DisplayName: Your user identifier
      Required: true
    - Name: sensors
      DisplayName: Log and read sensor data
      Required: false
    ApiResources:
    - Name: openid
      DisplayName: Your user identifier
      Enabled: true
      UserClaims:
      - Type: sub
      - Type: role
      Scopes:
      - Scope: openid
    - Name: houseapi
      DisplayName: Api for House Automation
      Enabled: true
      UserClaims:
      - Type: role
      Scopes:
      - Scope: sensors
    Clients:
    - ClientId: test-client
      ClientName: Test Client
      RequireClientSecret: true
      RequireConsent: false
      RequirePkce: false
      AllowedGrantTypes:
      - GrantType: password
      AllowedScopes:
      - Scope: openid
      - Scope: sensors
      ClientSecrets:
      - Type: EncodeSharedSecret
        Value: ClientPassword
    - ClientId: gateway-client
      ClientName: Gateway Client
      RequireClientSecret: true
      RequireConsent: false
      RequirePkce: false
      AllowOfflineAccess: true
      RefreshTokenUsage: ReUse
      UpdateAccessTokenClaimsOnRefresh: true
      AllowedGrantTypes:
      - GrantType: password
      AllowedScopes:
      - Scope: openid
      ClientSecrets:
      - Type: EncodeSharedSecret
        Value: GatewayPassword
    Roles:
    - DeviceCreate
    - DeviceRead
    - DeviceWrite
    - LogEntryRead
    - LogEntryWrite
    Users:
      admin@asp.net:
        Password: "@Password1"
        Roles:
        - DeviceCreate
        - DeviceWrite
        - DeviceRead
        - LogEntryRead
        - LogEntryWrite
Logging:
  LogLevel:
    Default: Debug
    System: Information
    Microsoft: Information
IdentityServer:
#  PublicOrigin: https://test.com
  SigningCredentialType: ecdsa
  ECDsa:
    Key: MHcCAQEEIGm1KV4Mow5wxBT9ee2k8nYIqnvczyvRmXZSsUk+tiBGoAoGCCqGSM49AwEHoUQDQgAEqcdqV5OWwM25DKXgN8cq5W0wrhcM9ghg7vXwDUEAinKkOYiZRxeKQEdof+Gb1J4mzraA4wQbnavdqMTLRkh92A==
    KeyId: hQPOjrNxT7u4oZrF7HdHD0tIL
#  X509:
#    Path: app_config/adamholt.us.pfx
#    Password: "D9sPIrxqwfQoW0XEw3SZ"

Kestrel:
  Endpoints:
    HTTP:
      Url: http://*:8181
